Lab24IdentitySQLMovieDatabase/Controllers/CheckedOutMoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab24IdentitySQLMovieDatabase.Data;

namespace Lab24IdentitySQLMovieDatabase.Models
{
    public class CheckedOutMoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CheckedOutMoviesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CheckedOutMovies
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.CheckedOutMovies.Include(c => c.Movie).Include(c => c.User);


            return View(await applicationDbContext.ToListAsync());
        }

        // GET: CheckedOutMovies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedOutMovies = await _context.CheckedOutMovies
                .Include(c => c.Movie)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (checkedOutMovies == null)
            {
                return NotFound();
            }

            return View(checkedOutMovies);
        }

        // GET: CheckedOutMovies/Create
        public IActionResult Create()
        {
            ViewData["MovieId"] = new SelectList(_context.Movies, "ID", "ID");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: CheckedOutMovies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,MovieId,DueDate")] CheckedOutMovies checkedOutMovies)
        {
            if (ModelState.IsValid)
            {
                _context.Add(checkedOutMovies);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "ID", "ID", checkedOutMovies.MovieId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", checkedOutMovies.UserId);
            return View(checkedOutMovies);
        }

        // GET: CheckedOutMovies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedOutMovies = await _context.CheckedOutMovies.FindAsync(id);
            if (checkedOutMovies == null)
            {
                return NotFound();
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "ID", "ID", checkedOutMovies.MovieId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", checkedOutMovies.UserId);
            return View(checkedOutMovies);
        }

        // POST: CheckedOutMovies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,MovieId,DueDate")] CheckedOutMovies checkedOutMovies)
        {
            if (id != checkedOutMovies.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(checkedOutMovies);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CheckedOutMoviesExists(checkedOutMovies.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "ID", "ID", checkedOutMovies.MovieId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", checkedOutMovies.UserId);
            return View(checkedOutMovies);
        }

        // GET: CheckedOutMovies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var checkedOutMovies = await _context.CheckedOutMovies
                .Include(c => c.Movie)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (checkedOutMovies == null)
            {
                return NotFound();
            }

            return View(checkedOutMovies);
        }

        // POST: CheckedOutMovies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var checkedOutMovies = await _context.CheckedOutMovies.FindAsync(id);
            _context.CheckedOutMovies.Remove(checkedOutMovies);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CheckedOutMoviesExists(int id)
        {
            return _context.CheckedOutMovies.Any(e => e.Id == id);
        }
    }
}

Lab24IdentitySQLMovieDatabase/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab24IdentitySQLMovieDatabase.Data;

namespace Lab24IdentitySQLMovieDatabase.Models
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MoviesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index( string searchString)
        {
            //return View(await _context.Movies.ToListAsync());
            var movies = from m in _context.Movies
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Title.Contains(searchString));
            }

            return View(await movies.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.ID == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Genre,Year,Actors,Directors,Runtime,Quantity")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Genre,Year,Actors,Directors,Runtime,Quantity")] Movie movie)
        {
            if (id != movie.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.ID == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.ID == id);
        }
        public async Task<IActionResult> CheckOut (int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.ID == id);
            if (movie == null)
            {
                return NotFound();
            }
            var user = HttpContext.User;
            var checkedOutMovies = new CheckedOutMovies()
            {
                DueDate = DateTime.Now.AddDays(2),
                MovieId = movie.ID,
                UserId = user.Identity.Name

            };
            _context.Add(checkedOutMovies);
            await _context.SaveChangesAsync();

            return View(checkedOutMovies);
        }
    }
}

Lab24IdentitySQLMovieDatabase/Views/Movies/Create.cshtml
@model Lab24IdentitySQLMovieDatabase.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="Genre" class="form-control"></select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Actors" class="control-label"></label>
                <input asp-for="Actors" class="form-control" />
                <span asp-validation-for="Actors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Directors" class="control-label"></label>
                <input asp-for="Directors" class="form-control" />
                <span asp-validation-for="Directors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Runtime" class="control-label"></label>
                <input asp-for="Runtime" class="form-control" />
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab24IdentitySQLMovieDatabase/Views/Movies/Delete.cshtml
@model Lab24IdentitySQLMovieDatabase.Models.Movie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Actors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Directors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Directors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Runtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Runtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lab24IdentitySQLMovieDatabase/Views/Movies/Details.cshtml
@model Lab24IdentitySQLMovieDatabase.Models.Movie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Actors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Directors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Directors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Runtime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Runtime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lab24IdentitySQLMovieDatabase/Views/Movies/Edit.cshtml
@model Lab24IdentitySQLMovieDatabase.Models.Movie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <select asp-for="Genre" class="form-control"></select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Actors" class="control-label"></label>
                <input asp-for="Actors" class="form-control" />
                <span asp-validation-for="Actors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Directors" class="control-label"></label>
                <input asp-for="Directors" class="form-control" />
                <span asp-validation-for="Directors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Runtime" class="control-label"></label>
                <input asp-for="Runtime" class="form-control" />
                <span asp-validation-for="Runtime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab24IdentitySQLMovieDatabase/Views/Movies/Index.cshtml
@model IEnumerable<Lab24IdentitySQLMovieDatabase.Models.Movie>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<form asp-controller="Movies" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString">
        <input type="submit" value="Search" />
    </p>
</form>
<form asp-controller="CheckedOutMovies" asp-action="Index">

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Genre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Year)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Actors)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Directors)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Runtime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Genre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Year)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Actors)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Directors)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Runtime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>

                    <td>
                        <a asp-action="CheckOut" asp-route-id="modelItem.ID">Check Out</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>